### PR TITLE
 #18 fix aggregated total count

### PR DESCRIPTION
**Pull request by helpse**

### CODE REVIEW

**Comment by helpse** [comment]
@Weakky Can you review this one?

**Comment by Weakky** [comment]
Hey there 👋

I'm gonna first merge #17, then do your work myself to prevent you from rebasing your work on top of it.

It should be done by the end of the day

**Comment by Weakky** [comment]
Done!

**Comment by helpse** [comment]
@Weakky Awesome! It works, thanks. Let me know if there's anything to help you with. I'd be glad to collaborate.

**Pull request closed without merging**
